# ===== Configuração do Servidor =====
server.port=8080

# URL de conexão (substitua 'nome_do_seu_banco' pelo nome real)
spring.datasource.url=jdbc:mysql://localhost:3306/Rocket_tlm?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA para MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Nome da aplicação =====
spring.application.name=Project Rocket 2026
