# ===== Configuração do Servidor =====
server.port=8080

# URL de conexão (substitua 'nome_do_seu_banco' pelo nome real)
spring.datasource.url=jdbc:h2:file:./daaata/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Configurações do Hibernate/JPA para MySQL

# ===== Nome da aplicação =====
spring.application.name=Project Rocket 2026

