# ===== Configuração do Servidor =====
server.port=8080

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/rocketdb
spring.datasource.username=postgres
spring.datasource.password=thyago08
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Nome da aplicação =====
spring.application.name=Project Rocket 2026
